import 'package:flutter/material.dart';

abstract class AppThemeColors {
  AppThemeColors._();
  static const Color primary = Color(0xFF1A3A2A);
  static const Color primaryLight = Color(0xFF2D5E3F);
  static const Color primarySurface = Color(0xFFE8F0EC);
  static const Color accent = Color(0xFFE8B84B);
  static const Color accentDark = Color(0xFFD4A030);
  static const Color background = Color(0xFFF5F0E4);
  static const Color surface = Color(0xFFFFFFFF);
  static const Color surfaceVariant = Color(0xFFF0EAD9);
  static const Color textPrimary = Color(0xFF1A1A1A);
  static const Color textSecondary = Color(0xFF6B6B6B);
  static const Color textLight = Color(0xFFFFFFFF);
  static const Color textMuted = Color(0xFF9E9E9E);
  static const Color success = Color(0xFF58CC02);
  static const Color error = Color(0xFFFF4B4B);
  static const Color divider = Color(0xFFE0D9CC);
  static const Color mapPointTeal = Color(0xFF4ECDC4);
  static const Color mapPointGreen = Color(0xFF1A3A2A);
  static const Color mapPointOrange = Color(0xFFFF9F43);
  static const Color mapPointYellow = Color(0xFFE8B84B);
  static const Color chatBubbleAI = Color(0xFFFFFFFF);
  static const Color chatBubbleUser = Color(0xFF1A3A2A);

  // legacy aliases
  static const Color primaryAccent = primary;
  static const Color secondaryAccent = accent;
  static const Color card = surface;
  static const Color primaryText = textPrimary;
  static const Color secondaryText = textSecondary;
  static const Color hintText = textMuted;
  static const Color inputBorder = divider;
  static const Color inputFill = surfaceVariant;
  static const Color button = primary;
  static const Color splashBackground = background;
  static const Color gold = accent;
  static const Color subtitleText = textSecondary;
  static const Color dividerText = divider;
  static const Color onboardingBackground = background;
  static const Color selected = primaryLight;
  static const Color border = divider;
  static const Color formCard = surface;
  static const Color warning = accentDark;
  static const Color info = primaryLight;
  static const Color activeEventDot = success;
  static const Color readingBackground = background;
  static const Color highlight = accent;
  static const Color bookmark = accentDark;
  static const Color google = Color(0xFFDB4437);
  static const Color apple = Color(0xFF000000);
  static const Color overlay = Color(0x66000000);
  static const Color shimmer = Color(0xFFEDEDED);
  static const Color photoSlot = surfaceVariant;
  static const Color tipsBackground = primarySurface;
  static const Color enrollDisabled = textMuted;
  static const Color tabUnselectedText = textSecondary;
  static const Color tabDivider = divider;
  static const Color gradientOverlay = overlay;
  static const Color activeCardBackground = primarySurface;
  static const Color activeCardBorder = primaryLight;
  static const Color archivedCardBackground = surfaceVariant;
  static const Color archivedCardBorder = divider;
  static const Color cardDateText = textSecondary;
  static const Color archivedTitle = textPrimary;
  static const Color archivedDate = textSecondary;
  static const double activeCardBackgroundOpacity = 1;
  static const double archivedCardBackgroundOpacity = 1;
  static const double archivedCardBorderOpacity = 1;
}
